### ISSUE TITLE
question

### ISSUE THREAD

**Issue by nathnial** [kklis/proxy#10]
I don't understand gcc option on the makefile. What is this option used for? Please! I wanna to know, but can't find in the google.

OPTFLAGS=-s -DUSE_SPLICE

**Comment by kklis** [comment]
It's used for conditional compilation https://github.com/kklis/proxy/blob/7034dd7e55e21c8a06424dfb633cb5f90c70c863/proxy.c#L349

**Comment by ticpu** [comment]
In fact, had this project have a build system of any kind, it could just enable it if the platform you're building on is supported as the only reason to disable it would be if the application had to modify the content of packets.  Not that I'm wishing for a build system, just adding that for completeness.

**Comment by nathnial** [comment]
thank you! thank you two brother very much.
