### ISSUE TITLE
Add `freeaddrinfo(res)` to prevent memory leak after `getaddrinfo` in `create_connection()` and `create_socket()`

### ISSUE THREAD

**Issue by gaurovgiri** [kklis/proxy#17]
**Description**:  
There is a potential memory leak in both `create_connection()` and `create_socket()` functions due to missing calls to `freeaddrinfo(res)` after resolving addresses using `getaddrinfo`. The `getaddrinfo` function dynamically allocates memory for the `addrinfo` structure, and failing to free it can lead to memory leaks.

**Steps to Reproduce**:  
1. Call `create_connection()` or `create_socket()` in a loop or multiple times.
2. Monitor memory usage using tools like `valgrind` or `top` to observe memory leak.

**Expected Behavior**:  
Memory allocated by `getaddrinfo()` should be freed after it's no longer needed by calling `freeaddrinfo(res)`.

**Actual Behavior**:  
`freeaddrinfo(res)` is missing in some code paths in both functions, leading to memory not being freed, which can accumulate over time.

**Relevant Code**:  

In `create_connection()`:
```c
if (getaddrinfo(remote_host, portstr, &hints, &res) != 0) {
    errno = EFAULT;
    return CLIENT_RESOLVE_ERROR;
}

// freeaddrinfo(res) is not called in case of success or failure.
```

In `create_socket()`:
```c
if (getaddrinfo(bind_addr, portstr, &hints, &res) != 0) {
    return CLIENT_RESOLVE_ERROR;
}

// Missing freeaddrinfo(res) if bind or socket creation fails.
```

**Proposed Fix**:  
1. Add `freeaddrinfo(res)` after the socket connection is established or in failure cases where it is missing.
2. Make sure the `addrinfo` structure is freed before the function returns to prevent memory leaks.

**Priority**: Medium  
**Severity**: Memory Leak

**Comment by gaurovgiri** [comment]
If you find this issue concerning, would love to contribute by resolving this.

**Comment by kklis** [comment]
Hi @gaurovgiri thank you very much for your analysis. If you have a working code that addresses this issue please open a pull request and I will review it.

**Comment by gaurovgiri** [comment]
Sure

**Comment by gaurovgiri** [comment]
Hey @kklis, I have created a PR. Please review it once. Thank you.

**Comment by kklis** [comment]
Thanks!
